---
abstract: 'Simple interface for User-Agent string parsing'
author:
  - 'Sean Cannon <dodger@cpan.org>'
  - 'Neil Bowers <neilb@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-ParseBrowser
requires:
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/HTML-ParseBrowser
  repository: https://github.com/neilbowers/HTML-ParseBrowser.git
version: '1.09'
