---
abstract: 'Simple interface for User-Agent string parsing'
author:
  - 'Dodger <dodger@>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords:
  - user-agent
  - browser
  - 'browser detection'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ParseBrowser
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.004
version: 1.03
