---
abstract: 'Simple interface for User-Agent string parsing'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
keywords:
  - user-agent
  - browser
  - 'browser detection'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ParseBrowser
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  perl: 5.004
resources:
  repository: https://github.com/neilbowers/HTML-ParseBrowser
version: 1.07
